[package]
org = "shammi"
name = "customerOrders"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "customerOrders"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"
